// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPF9Fu9PCVBSDJdxQnuVQtbDJXUDWpFqs',
    appId: '1:218254960737:web:605b536be3cecebad7a220',
    messagingSenderId: '218254960737',
    projectId: 'boook-store-f5faa',
    authDomain: 'boook-store-f5faa.firebaseapp.com',
    storageBucket: 'boook-store-f5faa.firebasestorage.app',
    measurementId: 'G-DDE3PZHG36',
    databaseURL: 'https://boook-store-f5faa-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40eP6VnuPS5wsl3mzYLMbIV0FnZFRLGk',
    appId: '1:218254960737:android:eb972ec23e40b70ed7a220',
    messagingSenderId: '218254960737',
    projectId: 'boook-store-f5faa',
    storageBucket: 'boook-store-f5faa.firebasestorage.app',
    databaseURL: 'https://boook-store-f5faa-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbnJ-7Mtfc41aytQ-S7jtr9XyXj317OkM',
    appId: '1:218254960737:ios:c697548b7b2f0e2ad7a220',
    messagingSenderId: '218254960737',
    projectId: 'boook-store-f5faa',
    storageBucket: 'boook-store-f5faa.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject2208e',
    databaseURL: 'https://boook-store-f5faa-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbnJ-7Mtfc41aytQ-S7jtr9XyXj317OkM',
    appId: '1:218254960737:ios:c697548b7b2f0e2ad7a220',
    messagingSenderId: '218254960737',
    projectId: 'boook-store-f5faa',
    storageBucket: 'boook-store-f5faa.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject2208e',
    databaseURL: 'https://boook-store-f5faa-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPF9Fu9PCVBSDJdxQnuVQtbDJXUDWpFqs',
    appId: '1:218254960737:web:998b6ad1ce64f59cd7a220',
    messagingSenderId: '218254960737',
    projectId: 'boook-store-f5faa',
    authDomain: 'boook-store-f5faa.firebaseapp.com',
    storageBucket: 'boook-store-f5faa.firebasestorage.app',
    measurementId: 'G-FBM0650G1K',
    databaseURL: 'https://boook-store-f5faa-default-rtdb.firebaseio.com/',
  );

}